name = "inertia_wisp_ssr"
version = "0.1.0"

description = "Server-side rendering support for inertia_wisp"
licences = ["MIT"]
repository = { type = "github", user = "jtdowney", repo = "inertia_wisp_ssr" }

[dependencies]
child_process = ">= 1.1.0 and < 2.0.0"
gleam_erlang = ">= 0.24.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_otp = ">= 0.9.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0"
inertia_wisp = ">= 0.2.1 and < 1.0.0"
logging = ">= 1.3.0 and < 2.0.0"
poolboy = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
