name = "hello_svelte"
version = "0.1.0"

[dependencies]
gleam_erlang = ">= 0.24.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_otp = ">= 0.9.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0"
inertia_wisp = ">= 0.2.1 and < 1.0.0"
inertia_wisp_ssr = { path = "../.." }
mist = ">= 5.0.0 and < 6.0.0"
nakai = ">= 1.1.2 and < 2.0.0"
shared = { path = "../shared" }
wisp = ">= 2.1.0 and < 3.0.0"
