name: CI

on:
  push:
  pull_request:

jobs:
  gleam:
    name: Gleam (${{ matrix.gleam }} OTP ${{ matrix.otp }} Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ["27", "28"]
        gleam: ["1.14"]
        node: ["22", "24"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          gleam-version: ${{ matrix.gleam }}
          rebar3-version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: gleam deps download
      - run: cd ssr_server && gleam deps download
      - run: cd ssr_server && gleam run -m esgleam/install
      - run: cd ssr_server && gleam build
      - run: cd ssr_server && gleam run -m build
      - run: gleam test
